### ISSUE TITLE
Plugin no loner works after FireFox upgrade to v51.0.1 (32-bit)

### ISSUE THREAD

**Issue by sionp** [firephp/firephp-extension#28]
Cannot see any output in the console window, despite FirePHP data being available in the HTTP response headers.

**Comment by sionp** [comment]
Update on this issue - it does still work, however, it now requires that the 'Shos CSS' errors option is switched on in the console options.

**Comment by morosanuae** [comment]
No, it still doesn't work even with that option turned on. No output to the console. Too many unresolved problems with this extension. It's seems to be abandoned. Maybe I should look elsewhere...

**Comment by lorenzos** [comment]
@morosanuae Same feeling here, and also Firebug itself is going to die, since developers and developing will be move to the Firefox internal dev tools (which btw it's not so bad, I think recently it because better than Firebug). Fortunately I found this:
https://github.com/ErikKrause/chromephp

It works well, and this fork in particular supports the same firephp API, so it should be easy for you to move on. I already did.

**Comment by jdlx** [comment]
@lorenzos … doesn't Chrome have an issue with (too) large headers?
I tried FirePHP4Chrome once, but it was fairly useless due to the header size restrictione …

**Comment by lorenzos** [comment]
You don't have to use Chrome! You can use ChromePhp on Firefox too, and you don't have to install any extension! 

That said, I don't know if Firefox have the same issue with headers too large. You can try.

**Comment by ianchanning** [comment]
@sionp I had tons of CSS warnings, so turning on 'Show CSS Errors' wasn't a good solution. However I have found that it also works by turning on 'Show JavaScript warnings'.

**Comment by cadorn** [comment]
A new FirePHP extension has been released that works for Firefox >= 56.0.2.

It also supports the ChromePHP/ChromeLogger protocol.

See: http://firephp.org/

**Comment by jdlx** [comment]
This is great news! THX Christoph!
